credentials:
  usernames:
    venkat:
      email: venkatmarine161@gmail.com
      name: Venkat
      password: "$2b$12$JyUlsFPAGxbMSF9YGMhUkOLRxH8JMuELMSTrJZlWHM132tiSmVo6i"
      password_reset: False   # 👈 This flag prompts password change if True

    demo_user:
      email: venkatmarine161@gmail.com
      name: Demo
      password: "$2b$12$PcIImfxMS2dgVa9EsgXUZeKeNFC7pxjs1GxlVBE4zJFTn66e8xV1C"
      password_reset: False  # 👈 No reset required

cookie:
  expiry_days: 30
  key: "random_signature_key"
  name: "random_cookie_name"